In [3]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7])
arr
type(arr)




numpy.ndarray

In [6]:
x=np.array([[1,2,3],[8,6,7]])#2d array
x

array([[1, 2, 3],
       [8, 6, 7]])

In [7]:
b=np.array([[1,3,2],[4,5,3],[6,7,5]])

In [8]:
b

array([[1, 3, 2],
       [4, 5, 3],
       [6, 7, 5]])

In [9]:
np.array([[1,2,3],[2,4,3],[8,9,7],[4,6,5]])

array([[1, 2, 3],
       [2, 4, 3],
       [8, 9, 7],
       [4, 6, 5]])

In [39]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr[0:8:2]

array([0, 2, 4, 6])

In [12]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(2,10,3)

array([2, 5, 8])

In [28]:
arr=np.arange(1,2,0.3)

In [29]:
arr

array([1. , 1.3, 1.6, 1.9])

In [32]:
arr[3]

1.9000000000000001

In [20]:
np.linspace(1,2,6)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [26]:
np.indices([4,5])

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [27]:
 np.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [55]:
 x = np.arange(30).reshape(3,2,5)

In [56]:
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [57]:
import numpy as np  
a = [[1, 2], [4, 1]] 

a




[[1, 2], [4, 1]]

In [58]:
b = [[4, 11], [2, 3]]  
c=np.dot(a, b)
c

array([[ 8, 17],
       [18, 47]])