In [1]:
import numpy as np
np.__version__

'1.16.5'

In [46]:
arr=np.array(     [ [   [1,2,3,4,5],[9,8,7,6,0]  ]     ,     [  [34,54,5,6,9],[21,34,5,34,5]   ]  ]   )# 2d array
print(arr)
print(arr.ndim)#number of dimantion
print(arr[0,1,3])

[[[ 1  2  3  4  5]
  [ 9  8  7  6  0]]

 [[34 54  5  6  9]
  [21 34  5 34  5]]]
3
6


In [22]:
a=np.array([[1,2,3,4,5],[9,8,7,6,0]])
print(a) 
print(a[0,4]+a[1,3])# acessing arra

[[1 2 3 4 5]
 [9 8 7 6 0]]
11
